"""Human-review exports (Excel workbook + CSVs) derived from a finished run's immutable artifacts.

Nothing here feeds back into the pipeline; the artifacts remain the source of truth.
"""
from __future__ import annotations

import csv
import json
from decimal import Decimal
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from utils.artifacts import CSV_MANIFEST, STAGE_FILES, verify_run
from utils.errors import PipelineError
from utils.safe import neutralize, strip_controls

STATUS_FILL = {"APPROVED": "C6EFCE", "FLAGGED": "FFEB9C", "MANUAL_REVIEW": "BDD7EE", "REJECTED": "FFC7CE"}
STATUS_LABEL = {"APPROVED": "Approved", "FLAGGED": "Flagged", "MANUAL_REVIEW": "Manual review", "REJECTED": "Rejected"}
SEVERITY_RANK = {"REJECTED": 0, "MANUAL_REVIEW": 1, "FLAGGED": 2, "APPROVED": 3}


def _num(v) -> float | None:
    return None if v is None else float(Decimal(str(v)))


SOURCE_LABEL = {
    "simulated": "SAMPLE DATA (random template)",
    "override": "SAMPLE DATA (planted demo scenario)",
    "portal": "Entered by employee in app",
}


def source_label(j: dict) -> str:
    if j.get("source") == "portal" and not j.get("submitted_at"):
        return "NOT SUBMITTED"
    return SOURCE_LABEL.get(j.get("source", "simulated"), "")


def _load(run_dir: Path):
    try:
        env = {s: json.loads((run_dir / STAGE_FILES[s]).read_text()) for s in (1, 2, 3)}
        manifest = json.loads((run_dir / CSV_MANIFEST).read_text())
        journal = list(csv.DictReader((run_dir / STAGE_FILES[4]).open(newline="")))
    except FileNotFoundError as exc:
        raise PipelineError(f"{run_dir.name} is incomplete ({exc.filename}); run all four stages first") from exc
    return env, manifest, journal


def auditor_kind(auditor: str | None) -> str:
    """'LLM' only when a real model produced the verdicts; the offline keyword heuristic must never be called an LLM."""
    return "LLM" if (auditor or "").startswith("llm-router") else "Mock auditor"


def provenance_note(items: list[dict], auditor: str | None = None) -> str | None:
    """Plain-language warning when any justification in the run is not real employee input."""
    fake = sum(1 for a in items if a["justified"]["justification"].get("source", "simulated") != "portal")
    if not fake:
        return None
    tail = ""
    if auditor is not None:
        tail = (" The LLM verdicts are real model output on that fake input." if auditor_kind(auditor) == "LLM"
                else " The verdicts come from an offline keyword heuristic (the mock auditor), not from an LLM.")
    return (f"SAMPLE DATA: the transactions, employees and policy are invented, and {fake} of {len(items)} justifications "
            f"were generated by the pipeline, not entered by employees.{tail}")


def _justification_detail(j: dict) -> str:
    if source_label(j) == "NOT SUBMITTED":
        return "No justification was submitted by the cardholder."
    r = j["receipt"]
    if r["present"] and r["total"]:
        receipt = f"${Decimal(r['total']):,.2f} from {r['vendor_name']}."
    else:
        receipt = "on file." if r["present"] else "none on file."
    attendees = f"Attendees: {', '.join(j['attendees'])}. " if j["attendees"] else ""
    who = "Loaded as sample data" if j.get("submitted_by") == "Sample data" else f"By {j.get('submitted_by') or 'unknown'}"
    return (f"{source_label(j)}. {who} at {_when(j) or 'unknown time'}. "
            f'Purpose: "{j["business_purpose"]}". {attendees}Receipt: {receipt}')


def _when(j: dict) -> str:
    return (j.get("submitted_at") or "").replace("T", " ")[:16]


def build_trace(run_dir: Path) -> dict[str, list[dict]]:
    """txn_id -> ordered list of {stage, step, detail, file}: the life of each transaction across the four stages."""
    env, _, journal = _load(run_dir)
    lines: dict[str, list[dict]] = {}
    for row in journal:
        lines.setdefault(row["txn_id"], []).append(row)
    trace: dict[str, list[dict]] = {}
    for a in env[3]["payload"]["items"]:
        r, t = a["justified"]["routed"], a["justified"]["routed"]["transaction"]
        j, l = a["justified"]["justification"], a.get("llm_result")
        amt = f"${Decimal(t['amount']):,.2f}"
        steps = [
            {"stage": 1, "step": "Bank statement row",
             "detail": f"{t['merchant_name']}, {amt}, posted {t['post_date']}, card ending {t['card_last4']}, MCC {t['mcc']}.",
             "file": STAGE_FILES[1]},
            {"stage": 1, "step": "Validated and routed",
             "detail": f"Passed schema checks. Card belongs to {r['employee_name']} ({r['department']}, cost center {r['cost_center']}); "
                       f"approver {r['approver_id'] or 'none'}." + ("" if r["employee_active"] else " WARNING: cardholder is no longer active."),
             "file": STAGE_FILES[1]},
            {"stage": 2, "step": "Justification submitted",
             "detail": _justification_detail(j),
             "file": STAGE_FILES[2]},
            {"stage": 3, "step": "Rule checks (Python, no LLM)",
             "detail": ("; ".join(f"{f['severity']} {f['code']}: {f['message']}" for f in a["findings"]) or "No rule findings.")
                       + f" Rule result: {STATUS_LABEL[a['deterministic_status']]}.",
             "file": STAGE_FILES[3]},
            {"stage": 3, "step": "LLM policy judgement" if auditor_kind(env[3]["payload"]["auditor"]) == "LLM"
                                 else "Mock auditor judgement (keyword heuristic, not an LLM)",
             "detail": (f"{l['verdict']} (confidence {l['confidence']:.2f}, sections {', '.join(l['policy_sections']) or 'none'}, via {l['served_by']}). {l['rationale']}"
                        if l else (f"LLM failed, sent to manual review: {a['llm_error']}" if a.get("llm_error")
                                   else "Skipped: no justification was submitted, so there was nothing to judge." if any(f["code"] == "MISSING_JUSTIFICATION" for f in a["findings"])
                                   else "Skipped: a hard rule already decided this transaction.")),
             "file": STAGE_FILES[3]},
            {"stage": 3, "step": "Final status",
             "detail": f"{STATUS_LABEL[a['final_status']]}. Rule: the worse of the rule result and the LLM verdict wins; the LLM can escalate but never downgrade.",
             "file": STAGE_FILES[3]},
            {"stage": 4, "step": "ERP journal lines",
             "detail": " | ".join(f"{'Dr' if float(x['debit']) else 'Cr'} {x['gl_account']} {x['gl_account_name']} {float(x['debit'] or 0) or float(x['credit']):,.2f}"
                                  for x in lines.get(a["txn_id"], [])) or "Not posted.",
             "file": STAGE_FILES[4]},
        ]
        trace[a["txn_id"]] = steps
    return trace


def build_tables(run_dir: Path) -> dict[str, tuple[list[str], list[list]]]:
    """Return {sheet name: (headers, rows)} for a run."""
    env, manifest, journal = _load(run_dir)
    s1, s3 = env[1]["payload"], env[3]["payload"]
    items = sorted(s3["items"], key=lambda a: (SEVERITY_RANK[a["final_status"]], -float(a["justified"]["routed"]["transaction"]["amount"])))

    kind = auditor_kind(s3["auditor"])
    txn_headers = ["Txn ID", "Date", "Cardholder", "Department", "Cost center", "Merchant", "MCC", "Category", "GL account (if approved)",
                   "Amount (USD)", "Receipt on file", "Receipt total", "Business purpose", "Attendees",
                   "Justification source", "Submitted by", "Submitted at",
                   "Rule status", "Rule findings", f"{kind} verdict", f"{kind} confidence", "Policy sections cited", f"{kind} rationale",
                   f"{kind} red flags", f"{kind} provider:model", f"{kind} error", "FINAL STATUS", "Posted to GL"]
    txn_rows, finding_rows = [], []
    for a in items:
        r, t = a["justified"]["routed"], a["justified"]["routed"]["transaction"]
        j, l = a["justified"]["justification"], a.get("llm_result") or {}
        posted = a["gl_account"] if a["final_status"] == "APPROVED" else "1450 (suspense)"
        txn_rows.append([
            a["txn_id"], t["post_date"], r["employee_name"], r["department"], r["cost_center"], t["merchant_name"], t["mcc"],
            a["category"], a["gl_account"], _num(t["amount"]),
            "Yes" if j["receipt"]["present"] else "No", _num(j["receipt"]["total"]), j["business_purpose"], "; ".join(j["attendees"]),
            source_label(j), j.get("submitted_by") or "", _when(j),
            STATUS_LABEL[a["deterministic_status"]], "; ".join(f"{f['code']}: {f['message']}" for f in a["findings"] if f["severity"] != "INFO"),
            l.get("verdict", ""), l.get("confidence"), ", ".join(l.get("policy_sections", [])), l.get("rationale", ""),
            ", ".join(l.get("red_flags", [])), l.get("served_by", ""), a.get("llm_error") or "",
            STATUS_LABEL[a["final_status"]], posted,
        ])
        for f in a["findings"]:
            finding_rows.append([a["txn_id"], t["merchant_name"], _num(t["amount"]), f["severity"], f["code"], f["message"]])

    trace = build_trace(run_dir)
    trace_rows = [[a["txn_id"], a["justified"]["routed"]["transaction"]["merchant_name"], n, st["stage"], st["step"], st["detail"], st["file"]]
                  for a in items for n, st in enumerate(trace[a["txn_id"]], start=1)]

    quarantine = [[q["row_number"], q["raw"].get("txn_id"), q["raw"].get("post_date"), q["raw"].get("card_last4"),
                   q["raw"].get("merchant_name"), q["raw"].get("amount"), q["raw"].get("currency"), " | ".join(q["reasons"])]
                  for q in s1["quarantined"]]

    j_headers = list(journal[0].keys()) if journal else []
    j_rows = [[_num(row[h]) if h in ("debit", "credit") else int(row[h]) if h == "line_no" else row[h] for h in j_headers] for row in journal]

    trail = [[s, STAGE_FILES[s], env[s]["meta"]["created_at"], env[s]["meta"]["payload_sha256"], env[s]["meta"]["upstream_sha256"] or ""]
             for s in (1, 2, 3)]
    trail.append([4, STAGE_FILES[4], "", manifest["csv_sha256"], manifest["upstream_sha256"]])

    counts = {k: sum(1 for a in items if a["final_status"] == k) for k in STATUS_LABEL}
    spend = {k: sum(float(a["justified"]["routed"]["transaction"]["amount"]) for a in items if a["final_status"] == k) for k in STATUS_LABEL}
    problems = verify_run(run_dir)
    note = provenance_note(items, s3["auditor"])
    summary = [
        *([["DATA WARNING", note], ["", ""]] if note else []),
        ["Run", run_dir.name], ["Statement period", f"{s1['statement_period_start']} to {s1['statement_period_end']}"],
        ["Auditor", s3["auditor"]], ["Journal ID", manifest["journal_id"]],
        ["Rows quarantined before audit", len(s1["quarantined"])], ["Transactions audited", len(items)],
        ["Control total (net, USD)", _num(s1["control_total_usd"])], ["Journal total debits = credits", _num(manifest["total_debits"])],
        ["Artifact hash chain", "VERIFIED" if not problems else "FAILED: " + "; ".join(problems)], ["", ""],
        ["Outcome", "Count / Spend (USD)"],
        *[[STATUS_LABEL[k], f"{counts[k]}  /  ${spend[k]:,.2f}"] for k in ("REJECTED", "MANUAL_REVIEW", "FLAGGED", "APPROVED")],
        ["", ""],
        ["SHEETS", ""],
        ["Trace", "Step-by-step life of every transaction across the four stages. Filter by Txn ID to follow one."],
        ["Transactions", "One row per audited transaction, most severe first. Start here. Read FINAL STATUS, then Rule findings and LLM rationale."],
        ["Findings", "One row per deterministic rule finding (limits, receipts, duplicates, splits, blocked categories)."],
        ["Quarantined", "Statement rows that failed validation and were excluded from audit and journal, with reasons."],
        ["ERP Journal", "Balanced double-entry lines. Approved spend posts to expense GL; everything else posts to 1450 until resolved."],
        ["Audit trail", "SHA-256 hash chain proving the artifacts were not modified."],
        ["", ""],
        ["STATUS MEANING", ""],
        ["Approved", "Passed every rule and the LLM judged the justification compliant."],
        ["Flagged", "Probably legitimate but a rule tripped or the justification is vague/incomplete; needs manager follow-up."],
        ["Manual review", "The LLM could not be reached or returned unusable output; a human must decide."],
        ["Rejected", "Clearly prohibited (blocked category, inactive cardholder) or the purpose itself violates policy."],
    ]
    return {
        "Read me": (["Item", "Value"], summary),
        "Transactions": (txn_headers, txn_rows),
        "Trace": (["Txn ID", "Merchant", "Step #", "Stage", "Step", "What happened", "Artifact"], trace_rows),
        "Findings": (["Txn ID", "Merchant", "Amount (USD)", "Severity", "Code", "Message"], finding_rows),
        "Quarantined": (["CSV row", "Txn ID", "Date", "Card last4", "Merchant", "Amount", "Currency", "Why rejected"], quarantine),
        "ERP Journal": (j_headers, j_rows),
        "Audit trail": (["Stage", "File", "Created (UTC)", "Payload SHA-256", "Upstream SHA-256"], trail),
    }


def _style(ws, headers: list[str], widths: dict[str, int]) -> None:
    head_fill = PatternFill("solid", fgColor="1E293B")
    for c in ws[1]:
        c.font, c.fill = Font(bold=True, color="FFFFFF"), head_fill
        c.alignment = Alignment(vertical="center", wrap_text=True)
    ws.freeze_panes = "B2"
    if ws.max_row > 1:
        ws.auto_filter.ref = ws.dimensions
    for i, h in enumerate(headers, start=1):
        ws.column_dimensions[get_column_letter(i)].width = widths.get(h, min(max(len(h) + 4, 12), 28))
    for row in ws.iter_rows(min_row=2):
        for c in row:
            c.alignment = Alignment(vertical="top", wrap_text=True)


def write_workbook(run_dir: Path, path: Path) -> Path:
    tables = build_tables(run_dir)
    wb = Workbook()
    wb.remove(wb.active)
    wide = {"Business purpose": 45, "What happened": 100, "Step": 28, "Justification source": 30, "Submitted at": 17, "Rule findings": 50, "LLM rationale": 60, "Message": 70, "Why rejected": 70, "Merchant": 24,
            "Attendees": 30, "Item": 34, "Value": 90, "Payload SHA-256": 68, "Upstream SHA-256": 68, "File": 30,
            "description": 40, "gl_account_name": 34}
    for name, (headers, rows) in tables.items():
        ws = wb.create_sheet(name)
        ws.append(headers)
        for row in rows:
            ws.append([strip_controls(v, keep="\n") if isinstance(v, str) else v for v in row])  # openpyxl raises on control chars
        for cells in ws.iter_rows():
            for c in cells:
                if isinstance(c.value, str) and c.data_type == "f":
                    c.data_type = "s"  # store as text: a value starting with "=" must never become a live formula
        _style(ws, headers, wide)
        for i, h in enumerate(headers, start=1):
            letter = get_column_letter(i)
            if h in ("Amount (USD)", "Receipt total", "debit", "credit"):
                for c in ws[letter][1:]:
                    c.number_format = '#,##0.00'
            if h == "LLM confidence":
                for c in ws[letter][1:]:
                    c.number_format = "0.00"
        status_cols = [i for i, h in enumerate(headers, start=1) if h in ("FINAL STATUS", "Rule status", "audit_status")]
        for row in ws.iter_rows(min_row=2):
            for i in status_cols:
                c = row[i - 1]
                key = str(c.value or "").upper().replace(" ", "_")
                if key in STATUS_FILL:  # text stays visible, fill is only reinforcement
                    c.fill = PatternFill("solid", fgColor=STATUS_FILL[key])
                    c.font = Font(bold=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path


def write_csvs(run_dir: Path, out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for name, (headers, rows) in build_tables(run_dir).items():
        p = out_dir / f"{name.lower().replace(' ', '_')}.csv"
        with p.open("w", newline="", encoding="utf-8-sig") as fh:  # BOM so Excel opens UTF-8 correctly
            w = csv.writer(fh)
            w.writerow(headers)
            w.writerows([[neutralize(v) for v in row] for row in rows])
        paths.append(p)
    return paths
